### ISSUE TITLE
iOS background player pause button bug

### ISSUE THREAD

**Issue by tomislav-s** [DoubleSymmetry/react-native-track-player#1046]
**Describe the bug**
When controlling playback on iOS via the background player everytime the `pause` button is pressed it causes a visual glitch where the progress slider and the current time get reset to the previous paused state for a short while.
The pause itself works normally, the glitch is purely visual.

It can be seen here:

![94440490-08dd9080-01a2-11eb-8dc4-6db8466ade83](https://user-images.githubusercontent.com/9304258/96103123-94ac2800-0ed7-11eb-9502-5df5de85361a.gif)

**To Reproduce**
1. Play a track on iOS
2. Navigate to the background player
3. Click the pause button
4. The progress bar handle, as well as the current time of the track glitches

**Environment (please complete the following information):**
React Native 0.63.2
React Native Track Player 1.2.3

Tested on 2 devices:
iPhone 11 Pro, iOS 13.7
iPhone 7, iOS 13.4.1

**Code**
```import TrackPlayer from 'react-native-track-player'

export const audioPlaybackService = async function () {
  TrackPlayer.addEventListener('remote-seek', (event) => {
    TrackPlayer.seekTo(event.position)
  })

  TrackPlayer.addEventListener('remote-play', () => {
    TrackPlayer.play()
  })

  TrackPlayer.addEventListener('remote-pause', () => {
    TrackPlayer.pause()
  })

  TrackPlayer.addEventListener('remote-previous', () => {
    TrackPlayer.skipToPrevious()
  })

  TrackPlayer.addEventListener('remote-next', () => {
    TrackPlayer.skipToNext()
  })
}
```

**Comment by Cuervo20** [comment]
The problem is not the background mode, the problem is the type of file you are using

**Comment by tomislav-s** [comment]
> The problem is not the background mode, the problem is the type of file you are using

@Cuervo20 The file i'm using is an mp3 loaded from a remote source - could you please elaborate more?

**Comment by Cuervo20** [comment]
I had a similar problem with an mp3 that was remote, but what happened to me is with (seekTo), the mp3 was going back to the beginning, so this is possibly the case as there are two types of mp3, a cbr mp3 and a vbr mp3. I attach an article about it, if this is not the case you can let me know without problems, I hope you can solve it

https://exoplayer.dev/troubleshooting.html#why-is-seeking-inaccurate-in-some-mp3-files

**Comment by serinuntius** [comment]
I was facing the same problem.

I didn't know I needed to set up capabilities.

I was fixed this way, I hope it helps you.

https://github.com/react-native-kit/react-native-track-player/blob/dev/example/react/screens/PlaylistScreen.js#L18-L31

```
await TrackPlayer.updateOptions({
    stopWithApp: true,
    capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
        TrackPlayer.CAPABILITY_STOP
    ],
    compactCapabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE
    ]
})
```

**Comment by tomislav-s** [comment]
> I had a similar problem with an mp3 that was remote, but what happened to me is with (seekTo), the mp3 was going back to the beginning, so this is possibly the case as there are two types of mp3, a cbr mp3 and a vbr mp3. I attach an article about it, if this is not the case you can let me know without problems, I hope you can solve it
> 
> https://exoplayer.dev/troubleshooting.html#why-is-seeking-inaccurate-in-some-mp3-files

Thanks for the reply!

Unfortunately from my understanding this isn't the case because the sample mp3 that I'm using doesn't seem to be VBR -  https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_1MG.mp3 it seems to have a constant bitrate of 320kbps.

**Comment by tomislav-s** [comment]
> I was facing the same problem.
> 
> I didn't know I needed to set up capabilities.
> 
> I was fixed this way, I hope it helps you.
> 
> https://github.com/react-native-kit/react-native-track-player/blob/dev/example/react/screens/PlaylistScreen.js#L18-L31
> 
> ```
> await TrackPlayer.updateOptions({
>     stopWithApp: true,
>     capabilities: [
>         TrackPlayer.CAPABILITY_PLAY,
>         TrackPlayer.CAPABILITY_PAUSE,
>         TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
>         TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
>         TrackPlayer.CAPABILITY_STOP
>     ],
>     compactCapabilities: [
>         TrackPlayer.CAPABILITY_PLAY,
>         TrackPlayer.CAPABILITY_PAUSE
>     ]
> })
> ```

@serinuntius thanks for the reply - this is my config object that I pass through `updateOptions` but the glitch occurs anyway

```
import TrackPlayer from 'react-native-track-player'

const defaultCapabilities = [
  TrackPlayer.CAPABILITY_PLAY,
  TrackPlayer.CAPABILITY_PAUSE,
  TrackPlayer.CAPABILITY_SEEK_TO,
  TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
  TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
]

export const trackPlayerOptions = {
  stopWithApp: true,
  capabilities: [...defaultCapabilities, TrackPlayer.CAPABILITY_STOP],
  notificationCapabilities: [...defaultCapabilities],
  compactCapabilities: [...defaultCapabilities],
}
```

**Comment by worldzb** [comment]
you can try

```
const defaultCapabilities = [
  TrackPlayer.CAPABILITY_PLAY,
  TrackPlayer.CAPABILITY_PAUSE,
  TrackPlayer.CAPABILITY_SEEK_TO,
  TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
  TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,

 TrackPlayer.CAPABILITY_PLAY,
  TrackPlayer.CAPABILITY_PAUSE,
  TrackPlayer.CAPABILITY_SEEK_TO,
  TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
  TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
]
```
Write Capabilities twice. I don’t know why at the moment, this should be a bug. This is how I solved it. Because I found that the last one of the array will become Readonly

**Comment by tomislav-s** [comment]
> you can try
> 
> ```
> const defaultCapabilities = [
>   TrackPlayer.CAPABILITY_PLAY,
>   TrackPlayer.CAPABILITY_PAUSE,
>   TrackPlayer.CAPABILITY_SEEK_TO,
>   TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
>   TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
> 
>  TrackPlayer.CAPABILITY_PLAY,
>   TrackPlayer.CAPABILITY_PAUSE,
>   TrackPlayer.CAPABILITY_SEEK_TO,
>   TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
>   TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
> ]
> ```
> 
> Write Capabilities twice. I don’t know why at the moment, this should be a bug. This is how I solved it. Because I found that the last one of the array will become Readonly

@worldzb thanks for the suggestion but unfortunately this didn't work for me - the bug is still present
