### ISSUE TITLE
Duplicate package names

### ISSUE THREAD

**Issue by mpivchev** [doublesymmetry/react-native-track-player#1418]
Hi, thanks for this great library.
I am working in a project that uses a other players that use old exoplayer dependencie and I having these kind of errors:

```
 Duplicate class com.google.android.exoplayer2.ui.WebViewSubtitleOutput$1 found in modules jetified-exoplayer-ui-2.14.2-runtime (com.google.android.exoplayer:exoplayer-ui:2.14.2) and jetified-exoplayer-ui-r2.16.4-runtime (com.github.DoubleSymmetry.ExoPlayer:exoplayer-ui:r2.16.4)

 Duplicate class com.google.android.exoplayer2.video.spherical.CameraMotionListener found in modules jetified-exoplayer-core-2.14.2-runtime (com.google.android.exoplayer:exoplayer-core:2.14.2) and jetified-exoplayer-core-r2.16.4-runtime (com.github.DoubleSymmetry.ExoPlayer:exoplayer-core:r2.16.4)
```

It is because Kotlin audio is using the same "com.google.android.exoplayer2" package name, maybe could be it changed for future versions to avoid the conflict ?

_Originally posted by @SystemBlad in https://github.com/DoubleSymmetry/react-native-track-player/discussions/1264#discussioncomment-2185744_

**Comment by hammadwahab12** [comment]
This issue is still open in 2.2.0-rc3 version @mpivchev can you please let me know when this can be fixed. Thanks

**Comment by rajpootathar** [comment]
Still facing the same issue on my end (with 2.2.0-rc3 version).
Further [details ](https://github.com/DoubleSymmetry/react-native-track-player/discussions/1264#discussioncomment-2264733)

**Comment by mpivchev** [comment]
Hi, currently working on #1447. I will pick this issue up after this. If one of you wants to contribute to this issue so we can get it out sooner, we would greatly appreciate it :)

**Comment by hammadwahab12** [comment]
Hello @mpivchev, any update ?

**Comment by mpivchev** [comment]
@hammadwahab12 It's still in our to-do list. As mentioned before, if you want this resolved quicker, you are welcome to contribute.

**Comment by jspizziri** [comment]
Track this PR which should ultimately resolve this issue:  https://github.com/doublesymmetry/KotlinAudio/pull/33

**Comment by KrisLau** [comment]
@jspizziri Thanks for all the awesome work!

**Comment by stereodenis** [comment]
I downgraded to 2.1.3, and it works with react-native-video v5.2.0

**Comment by KrisLau** [comment]
@stereodenis So 2.1.3 was the original version I was using but that version gives me a different problem (Could not find com.google.android.exoplayer:exoplayer-core:2.11.4) which was fixed in [v2.2.0-rc3](https://github.com/doublesymmetry/react-native-track-player/releases/tag/v2.2.0-rc3)

**Comment by stereodenis** [comment]
@KrisLau I have no sound in videos on android with the workaround from the comment

**Comment by Hannes1** [comment]
I saw a @dcvz  mentioning that you can handle resolution conflicts with [gradle](https://docs.gradle.org/current/userguide/resolution_rules.html#sec:dependency_resolve_rules), so I came up with the following fix, don't know if there's a better way than replacing one by one but anyways this works till they move away from their work


```gradle

//Add this to the dependencies object in app/build.gradle
    modules {
        module("com.google.android.exoplayer:exoplayer") {
            replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer", "replace exoplayer with doublesymmetry.Exoplayer")
        }
        module("com.google.android.exoplayer:exoplayer-core") {
            replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-core", "replace exoplayer with doublesymmetry.Exoplayer")
        }
        module("com.google.android.exoplayer:exoplayer-ui") {
            replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-ui", "replace exoplayer with doublesymmetry.Exoplayer")
        }
        module("com.google.android.exoplayer:exoplayer-common") {
            replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-common", "replace exoplayer with doublesymmetry.Exoplayer")
        }
        module("com.google.android.exoplayer:exoplayer-smoothstreaming") {
            replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-smoothstreaming", "replace exoplayer with doublesymmetry.Exoplayer")
        }
        module("com.google.android.exoplayer:exoplayer-hls") {
            replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-hls", "replace exoplayer with doublesymmetry.Exoplayer")
        }
        module("com.google.android.exoplayer:exoplayer-dash") {
            replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-dash", "replace exoplayer with doublesymmetry.Exoplayer")
        }
        
    }
```

## Disclaimer
I only use expo-av (that also uses exo-player) for permissions and everything is working, so I'm not certain what they changed with their fork and if using this fork will break other packages

**Comment by DennisdeWitNL** [comment]
@Hannes1 I added you code to android/app/build.gradle. But it is still not working. Could you please post me an example?

**Comment by Hannes1** [comment]
@DennisdeWitNL  What error do you get? I don't have an example app at the momement I'll see If I have time this weekend

**Comment by DennisdeWitNL** [comment]
> @DennisdeWitNL What error do you get? I don't have an example app at the momement I'll see If I have time this weekend

There are the errors:

```
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.exoplayer2.database.BuildConfig found in modules jetified-exoplayer-database-2.17.1-runtime (com.google.android.exoplayer:exoplayer-database:2.17.1) and jetified-exoplayer-database-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-database:r2.17.2)
     Duplicate class com.google.android.exoplayer2.database.DatabaseIOException found in modules jetified-exoplayer-database-2.17.1-runtime (com.google.android.exoplayer:exoplayer-database:2.17.1) and jetified-exoplayer-database-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-database:r2.17.2)
     Duplicate class com.google.android.exoplayer2.database.DatabaseProvider found in modules jetified-exoplayer-database-2.17.1-runtime (com.google.android.exoplayer:exoplayer-database:2.17.1) and jetified-exoplayer-database-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-database:r2.17.2)
     Duplicate class com.google.android.exoplayer2.database.DefaultDatabaseProvider found in modules jetified-exoplayer-database-2.17.1-runtime (com.google.android.exoplayer:exoplayer-database:2.17.1) and jetified-exoplayer-database-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-database:r2.17.2)
     Duplicate class com.google.android.exoplayer2.database.ExoDatabaseProvider found in modules jetified-exoplayer-database-2.17.1-runtime (com.google.android.exoplayer:exoplayer-database:2.17.1) and jetified-exoplayer-database-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-database:r2.17.2)
     Duplicate class com.google.android.exoplayer2.database.StandaloneDatabaseProvider found in modules jetified-exoplayer-database-2.17.1-runtime (com.google.android.exoplayer:exoplayer-database:2.17.1) and jetified-exoplayer-database-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-database:r2.17.2)
     Duplicate class com.google.android.exoplayer2.database.VersionTable found in modules jetified-exoplayer-database-2.17.1-runtime (com.google.android.exoplayer:exoplayer-database:2.17.1) and jetified-exoplayer-database-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-database:r2.17.2)
     Duplicate class com.google.android.exoplayer2.database.package-info found in modules jetified-exoplayer-database-2.17.1-runtime (com.google.android.exoplayer:exoplayer-database:2.17.1) and jetified-exoplayer-database-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-database:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.AssetDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.BaseDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.BuildConfig found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.ByteArrayDataSink found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.ByteArrayDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.ContentDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.ContentDataSource$Api31 found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.ContentDataSource$ContentDataSourceException found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DataSchemeDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DataSink found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DataSink$Factory found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DataSource$Factory found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DataSourceException found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DataSourceInputStream found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DataSourceUtil found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DataSpec found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DataSpec$1 found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DataSpec$Builder found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DataSpec$Flags found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DataSpec$HttpMethod found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DefaultDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DefaultDataSource$Factory found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DefaultDataSourceFactory found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DefaultHttpDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DefaultHttpDataSource$1 found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DefaultHttpDataSource$Factory found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DefaultHttpDataSource$NullFilteringHeadersMap found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.DummyDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.FileDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.FileDataSource$Api21 found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.FileDataSource$Factory found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.HttpDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.HttpDataSource$BaseFactory found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.HttpDataSource$CleartextNotPermittedException found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.HttpDataSource$Factory found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException$Type found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.HttpDataSource$InvalidContentTypeException found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.HttpDataSource$RequestProperties found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.HttpUtil found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.PriorityDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.PriorityDataSource$Factory found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.PriorityDataSourceFactory found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.RawResourceDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.RawResourceDataSource$RawResourceDataSourceException found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.ResolvingDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.ResolvingDataSource$Factory found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.ResolvingDataSource$Resolver found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.StatsDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.TeeDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.TransferListener found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.UdpDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.UdpDataSource$UdpDataSourceException found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.Cache found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.Cache$CacheException found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.Cache$Listener found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheDataSink found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheDataSink$CacheDataSinkException found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheDataSink$Factory found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheDataSource$1 found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheDataSource$CacheIgnoredReason found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheDataSource$EventListener found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheDataSource$Factory found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheDataSource$Flags found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheEvictor found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheFileMetadata found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheFileMetadataIndex found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheKeyFactory found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheSpan found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheWriter found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CacheWriter$ProgressListener found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CachedContent found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CachedContent$Range found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CachedContentIndex found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CachedContentIndex$DatabaseStorage found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CachedContentIndex$LegacyStorage found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.CachedContentIndex$Storage found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.ContentMetadata found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.ContentMetadataMutations found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.DefaultContentMetadata found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.LeastRecentlyUsedCacheEvictor found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.NoOpCacheEvictor found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.ReusableBufferedOutputStream found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.SimpleCache found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.SimpleCache$1 found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.SimpleCacheSpan found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.cache.package-info found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.crypto.AesCipherDataSink found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.crypto.AesCipherDataSource found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.crypto.AesFlushingCipher found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.crypto.package-info found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     Duplicate class com.google.android.exoplayer2.upstream.package-info found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.
```

**Comment by Hannes1** [comment]
@DennisdeWitNL Okay so you need to replace more modules because your package uses more of exoplayers modules

For example
```
Duplicate class com.google.android.exoplayer2.database.BuildConfig found in modules jetified-exoplayer-database-2.17.1-runtime (com.google.android.exoplayer:exoplayer-database:2.17.1) and jetified-exoplayer-database-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-database:r2.17.2)
```
You'll have to replace the following `com.google.android.exoplayer:exoplayer-database:2.17.1` as well with the following:
```
module("com.google.android.exoplayer:exoplayer-database") {
            replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-database", "replace exoplayer with doublesymmetry.Exoplayer")
}
```

Just go through your error logs and see what yo need to replace further

**Comment by DennisdeWitNL** [comment]
@Hannes1 I have successfully replaced database, but still I have this problem.

``
com.google.android.exoplayer2.upstream
``

So I thought I would have to do this:

``
            module("com.google.android.exoplayer:exoplayer-upstream") {
            replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-upstream", "replace exoplayer with doublesymmetry.Exoplayer")
        }
``

But that didn't help. Any other ideas?

**Comment by Hannes1** [comment]
@DennisdeWitNL You are probably looking at the wrong thing

Example
```
 Duplicate class com.google.android.exoplayer2.upstream.crypto.AesCipherDataSink found in modules jetified-exoplayer-datasource-2.17.1-runtime (com.google.android.exoplayer:exoplayer-datasource:2.17.1) and jetified-exoplayer-datasource-r2.17.2-runtime (com.github.doublesymmetry.Exoplayer:exoplayer-datasource:r2.17.2)
```

The problem isn't with `class com.google.android.exoplayer2.upstream` the conflict is with what is in the brackets (): `(com.google.android.exoplayer:exoplayer-datasource:2.17.1)`

So the conflicting module is: `exoplayer-datasource`

**Comment by stereodenis** [comment]
still facing issue with react-native-video@5.2.0 + react-native-track-player@3.0.0
https://gist.github.com/stereodenis/8ffe0a7e22a403f94746161253ec9dbb

**Comment by Hannes1** [comment]
> still facing issue with react-native-video@5.2.0 + react-native-track-player@3.0.0
> https://gist.github.com/stereodenis/8ffe0a7e22a403f94746161253ec9dbb

See the [workaround](https://github.com/doublesymmetry/react-native-track-player/issues/1418#issuecomment-1212769004) for now @stereodenis

**Comment by Hannes1** [comment]
@stereodenis mmm this might be a react native video issue, it mentions turbomodules does the package support turbomodules?

Or does react native video work without react native track player changes?

**Comment by stereodenis** [comment]
@Hannes1 it works for me on 6.0.0-alpha1, but not on 5.2.0

**Comment by russriser** [comment]
If anyone needs to do this in a Managed Expo project, here's a config plugin that will replace the dependencies:

`const { withAppBuildGradle } = require('@expo/config-plugins');

const replaceDependencies = (fileContent) => {
  const insertString = `
    dependencies {
        modules {
            module("com.google.android.exoplayer:exoplayer") {
                replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer", "replace exoplayer with doublesymmetry.Exoplayer")
            }
            module("com.google.android.exoplayer:exoplayer-core") {
                replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-core", "replace exoplayer with doublesymmetry.Exoplayer")
            }
            module("com.google.android.exoplayer:exoplayer-ui") {
                replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-ui", "replace exoplayer with doublesymmetry.Exoplayer")
            }
            module("com.google.android.exoplayer:exoplayer-common") {
                replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-common", "replace exoplayer with doublesymmetry.Exoplayer")
            }
            module("com.google.android.exoplayer:exoplayer-smoothstreaming") {
                replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-smoothstreaming", "replace exoplayer with doublesymmetry.Exoplayer")
            }
            module("com.google.android.exoplayer:exoplayer-hls") {
                replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-hls", "replace exoplayer with doublesymmetry.Exoplayer")
            }
            module("com.google.android.exoplayer:exoplayer-dash") {
                replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-dash", "replace exoplayer with doublesymmetry.Exoplayer")
            }
            module("com.google.android.exoplayer:exoplayer-database") {
                replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-database", "replace exoplayer with doublesymmetry.Exoplayer")
            }
            module("com.google.android.exoplayer:exoplayer-datasource") {
                replacedBy("com.github.doublesymmetry.Exoplayer:exoplayer-datasource", "replace exoplayer with doublesymmetry.Exoplayer")
            }
        }
    }
`;
  const startIndex = fileContent.indexOf('splits {');
  return `${fileContent.slice(0, startIndex)}${insertString}\n\t${fileContent.slice(startIndex)}`;
}

const withRNTP = (initialConfig) =>
  withAppBuildGradle(initialConfig, (config) => {
    const updatedFile = replaceDependencies(config.modResults.contents);
    config.modResults.contents = updatedFile;
    return config;
  });

module.exports = withRNTP;`

**Comment by KrisLau** [comment]
@russriser the changes that fix this are merged in https://github.com/doublesymmetry/KotlinAudio/pull/38.  Just need to wait for it to be included in a new version

**Comment by mpivchev** [comment]
This should be fixed in 3.1.0. If you still have issues, please reopen this.

**Comment by waheedakhtar694** [comment]
@mpivchev still facing the issue in 3.2.0.

**Comment by ahmadsyed** [comment]
+1 me too, using  rntp ^3.2.0 and react-native-video ^5.2.1 .

In react-native-video I had to add these two lines in settings.gradle to play my encrypted video 

```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

but after these lines I am getting above conflict , RNV package is using exoplayer:2.13.3
